//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCAsp_Lot.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class evento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public evento()
        {
            this.tarjetas = new HashSet<tarjeta>();
        }
    
        public int id { get; set; }

        [Required(ErrorMessage = "Title is required")]
        [Display(Name = "Event Title")]
        public string title { get; set; }

        [Required(ErrorMessage = "Body is required")]
        [Display(Name = "Event Body")]
        public string body { get; set; }


        [Required(ErrorMessage = "Start time is required")]
        [Display(Name = "Start Time")]
        public System.DateTime start_time { get; set; }
        public System.DateTime finish_time { get; set; }
        [Range(0, 1, ErrorMessage = "Passed must be choose 0 or 1")]
        public Nullable<byte> passed { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tarjeta> tarjetas { get; set; }
    }
}
